/*

    THIS IS THE SETTINGS FILE

    Explained:

    Twitch:

    channel = the channel you want to control scenes in

    Chat:
    
    If you want the bot to respond at all (to confirm scene changes or tell 
    non-mods they can't use it), you need to fill in username and oauthtoken.

    username = the username of your bot account.
    token - a token generated by https://twitchapps.com/tmi/
            use this website to generate the token by connecting the
            account, you have to use the same account as 'username'.

    They're not required!

    OBS:

    These are set to the defaults of the websockets plugin. 
    Don't change them unless you want to!

    If you do change them, set these to match what you 
    set on the websockets plugin in OBS.



*/

var twitchSettings = {
    channel : "channelname"
}

var chatSettings = {
    service: "",    
    token : ""
}

var obsSettings = {
    url : "localhost",
    port: "4444",
    password : "",
    sceneList : ["scene1", "scene2", "scene3"]
}